name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: npm install
      - name: Publish To NPM
        with:
          credentials: ${{secrets.NPM_TOKEN}}
        run: npm run publish -- --config=release
